### ISSUE TITLE
Cannot import 'weight' from recurrentshop

### ISSUE THREAD

**Issue by xrw** [farizrahman4u/seq2seq#172] opened 2017-04-20 15:38 UTC
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "./test.py", line 1, in <module>
    from seq2seq import SimpleSeq2Seq, Seq2Seq, AttentionSeq2Seq
  File "/usr/local/lib/python2.7/dist-packages/seq2seq/__init__.py", line 1, in <module>
    from .cells import *
  File "/usr/local/lib/python2.7/dist-packages/seq2seq/cells.py", line 1, in <module>
    from recurrentshop import RNNCell, LSTMCell, weight
ImportError: cannot import name weight
```

Above is what I got. I double checked the recurrentshop, and nothing is related to 'weight'. Is there anything updates in recurrentshop? Hopefully we could fix this problem.

Thanks!

**Comment by brannondorsey** [comment] 2017-04-20 17:00
Looks like a dupe of https://github.com/farizrahman4u/seq2seq/issues/171. I am also experiencing this problem.

**Comment by abhaikollara** [comment] 2017-04-21 06:51
RecurrentShop 1.0 has been released, includes some major API changes, check it out

**Comment by skeydan** [comment] 2017-04-23 15:52
Ah ok, I've found a thread for the problem I have. I'm joining in order to get notifications when to update the libraries.

**Comment by jia-zh** [comment] 2017-04-26 13:05
I have the same problem.

**Comment by gy2029979** [comment] 2017-05-04 15:03
Is there an update for this problem?
I found the same problem.

**Comment by PraveenKumarCSE** [comment] 2017-05-05 10:33
Hi folks...
     Finally I found the solution for "**ImportError: cannot import name weight**". Latest recurrentshop lib has no weight function. So only that error is throwing. finally I found another recurrentshop lib with weight function. Please download lib from following link and recompile the recurrentshop. Then try to run.
Link : https://github.com/sunnysai12345/recurrentshop

**Closed** 2017-06-03 23:30 UTC
