### ISSUE TITLE
_preprocess_function error 

### ISSUE THREAD

**Issue by SuperYm** [farizrahman4u/seq2seq#222] opened 2017-09-26 10:26 UTC
import seq2seq
from seq2seq.models import SimpleSeq2Seq

model = SimpleSeq2Seq(input_dim=5, hidden_dim=10, output_length=8, output_dim=8)
model.compile(loss='mse', optimizer='rmsprop')

 File "/usr/local/lib/python2.7/dist-packages/recurrentshop/engine.py", line 659, in preprocess_input
    if self._preprocess_function is None:
AttributeError: 'RecurrentSequential' object has no attribute '_preprocess_function'.
how can i slove this?

**Comment by walmsley** [comment] 2017-09-26 20:28
👍  also just encountered this error, please help.

**Comment by walmsley** [comment] 2017-09-26 20:29
This seems to be a duplicate of #221

**Comment by walmsley** [comment] 2017-09-26 22:19
temporary workaround: install old version of recurrentshop: `pip install git+https://github.com/datalogai/recurrentshop.git@f5a1d126dd579c1eefe7c7caaa4ccd8867ee09d4`

**Comment by SuperYm** [comment] 2017-09-27 02:22
the current master-version has this problem,use branch version and problem sloved.

**Closed** 2017-09-28 01:51 UTC
